spring:
  application:
    name: ARTICLE-SERVICE

  datasource:
    url: jdbc:mysql://192.168.1.20:3306/articlesDb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    url: jdbc:mysql://localhost:3306/articlesDb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: alex
    password: Sofia@1005

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 4002


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.49.2:31002/eureka/
#      defaultZone: http://172.17.0.2:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: 192.168.49.2
#    hostname: 192.168.1.20
#    hostname: localhost

